
# MongoDB Atlas connection
[mongo]
uri = "mongodb+srv://<username>:<password>@cluster0.xxxxx.mongodb.net/LEONI?retryWrites=true&w=majority"

# File paths (adjust for Streamlit Cloud)
[paths]
rosenberger_images = "data/rosenberger/images"
rosenberger_csv = "data/rosenberger/donnees_brutes.csv"
rosenberger_clusters = "data/rosenberger/clusters_groupes.csv"
md_elektronik_images = "data/md_elektronik/images"
md_elektronik_csv = "data/md_elektronik/donnees_brutes.csv"
md_elektronik_clusters = "data/md_elektronik/clusters_groupes.csv"
